server:
  port: 8080

jwt:
  secret: "7db95ebb50d1969b9540606cd4366373"   # keep outside source control
  access-token-expiration-ms: 900000    # 15 minutes
  refresh-token-expiration-ms: 2592000000  # 30 days (example)

spring:
  application:
    name: java-hexagonal

  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000

  cache:
    type: none # disable default, we use custom composite

  security:
    user:
      name: ntdat104
      password: 123

  messages:
    basename: errors
    encoding: UTF-8

  datasource:
    # H2 Database (in-memory)
    url: jdbc:h2:mem:javahexagonal
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true

  # MySQL (optional - uncomment if needed)
  # datasource:
  #   url: jdbc:mysql://localhost:3306/springboot
  #   username: root
  #   password: mauFJcuf5dhRMQrjj
  # jpa:
  #   show-sql: true
  #   hibernate:
  #     ddl-auto: create-drop
  #   properties:
  #     hibernate:
  #       dialect: org.hibernate.dialect.MySQL5Dialect
  #       format_sql: true

  # Async task executor configuration
  task:
    execution:
      thread-name-prefix: "AsyncExecutor-"
      pool:
        core-size: 5
        max-size: 10
        queue-capacity: 10000
    scheduling:
      thread-name-prefix: "core-scheduling-"
      pool:
        size: 2

logging:
  pattern:
    level: '%5p [${RequestKeyConstant.X_REQUEST_ID:-},%X{requestId}]'
